services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    # develop:
    #  watch:
    #   - action: sync
    #      path: ./frontend
    #      target: /app
    #      ignore:
    #        - node_modules/
    #    - action: rebuild
    #      path: ./frontend/package.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      # - ./backend:/app
      - /app/.venv
      - uv-cache:/root/.cache/uv
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: ./backend/pyproject.toml

volumes:
  uv-cache:
