services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    volumes:
      - ./:/frontend:/app
      - node_modules:/frontend:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  node_modules:
