services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    volumes:
      - ./frontend:/app:delegated
      - ./frontend/.tanstack/tmp:/app/.tanstack/tmp
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - TMPDIR=/app/.tanstack/tmp
      - CHOKIDAR_USEPOLLING=true # for Vite’s file watcher over Docker mounts
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  frontend_node_modules:
